baseURL = "https://galexite.uk/"
languageCode = "en-gb"
languageLang = "en"
title = "galexite.uk"

[params]
description = "Third year Computer Science student with a fair few side projects."

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[menu]

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/posts/"
